### ISSUE TITLE
PIO and AG Improvements

### ISSUE THREAD

**Issue by jcollins-atx** [jcollins-atx/duf-property-preview#20]
### Task List
- [ ] Modify aerial imagery slider label
- [ ] Parcel table number right align
- [ ] Change all instances of "impervious cover features" to just "features"
- [ ] Filtering language
- [ ] Exclusion reason: none -- better wording?
- [ ] Minor word mistakes (missing words, "rate payer" in disclaimer, remove generated by in links dropdown)

### View Box
At first, I thought “Aerial Imagery (2017)” was a headline for the bar, which confused me. My inclination would be to put “Aerial imagery from 2017” at the bottom of the box and not bold it. Over the bar, I would put a headline Adjust Brightness or Brightness Level with the customary icon for brightness. Or just use the icon with the bar.

### Right-Hand Sidebar
In the “About this Preview” box – you’re missing an “is” on the 4th line between “what” and “displayed”

Under “Proposed Edits and Totals” --  I suggest right aligning the numbers in the chart

Under “Impervious Area Breakdown:”
- You’re missing a “to” between “contributes” and “the” on the second line. 
- For readability, I would also consider just referring to “features” rather than “impervious cover features” throughout. I think most people will comprehend “features” but may find “impervious cover features” confusing, making the whole sentence less easy to understand. This means the first line would read, “This figure shows the relative amount each feature contributes to…” This is a change that I would recommend every time the phrase occurs throughout the tool. If this changes concerns you, you could add a sentence, “Only features that contribute to the impervious cover total are included in the graph” or something along those lines. 
- I’m concerned the bar graph may be confusing for people. I found the lack of labels (until you hover) a little challenging and the scale line a little confusing. It took me a moment to realize it wasn’t supposed to line up with the sections. I wonder if a bulleted list or a pie chart would be better.

Under “Proposed Edits” – some users may be confused by the filter option. Maybe add some language to explain: The table below shows all the features. Use the filter option to adjust the chart to show a subset of features, such as only those features with proposed edits. (Note: I didn’t notice the default originally and am guessing it was everything. Please change the language as necessary!)

In the disclaimer, I think “ratepayers” should be two words.

Under “How to Use,” under “review summaries” I would change the second “and” to a comma: “parcel totals, estimates and impervious cover”

Under “Explore mapped impervious cover” – should “Currently” be “Current”?

### Map
Most of the boxes I clicked on had a line “Exclusion Reason: None.” I wasn’t sure what this meant. I’m not sure you need to change it, but wanted to let you know that you may get questions about it. 

### Links
All the links worked for me. I wasn’t sure that the “generated by” belonged under links. It seems link it would be more usual at the bottom somewhere. I’m not sure you need to change it, but it’s something to consider.
